unit-converter/config/routes.rb
Rails.application.routes.draw do
  # resource :unit_converter, only: %i[create]
  # resolve("UnitConventer") { [ :unit_converter ] }
  get "/unit_converter", to: "unit_converter#show"
  post "/unit_converter", to: "unit_converter#create", as: :operation

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "unit_converter#show"
end

unit-converter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

unit-converter/app/controllers/unit_converter_controller.rb
class UnitConverterController < ApplicationController
  before_action :set_conversions

  VALID_CONVERSIONS = {
    weight: [
      [ "Kilograms", "kg" ],
      [ "Grams", "g" ],
      [ "Milligrams", "mg" ],
      [ "Pounds", "lb" ],
      [ "Ounces", "oz" ]
    ],
    length: [
      [ "Millimeters", "mm" ],
      [ "Centimeters", "cm" ],
      [ "Meters", "m" ],
      [ "Kilometers", "km" ],
      [ "Inches", "in" ],
      [ "Feet", "ft" ],
      [ "Yards", "yd" ],
      [ "Miles", "mi" ]
    ],
    temperature: [
      [ "Celsius", "C" ],
      [ "Kelvin", "K" ],
      [ "Fahrenheit", "F" ]
    ],
    volume: [
      [ "Milliliters", "ml" ],
      [ "Liters", "l" ],
      [ "Cubic Meters", "m3" ],
      [ "Cubic Centimeters", "cm3" ],
      [ "Gallons", "gal" ],
      [ "Quarts", "qt" ],
      [ "Pints", "pt" ],
      [ "Fluid Ounces", "fl oz" ]
    ]
  }

  def show
  end

  def create
    @type = params[:type].to_sym
    value = params[@type]
    unit_from = params[:unit_from]
    unit_to = params[:unit_to]

    @type_value = Float(value, exception: false)
    if @type_value.nil?
      flash[:alert] = "'#{value}' is an invalid input, use numbers only!"
      return render :show, status: :unprocessable_content
    end

    if VALID_CONVERSIONS.key?(@type)
      @results = perform_conversion(@type, @type_value, unit_from, unit_to)
      render :show, status: :ok
    else
      flash[:error] = "Invalid conversion type."
      render :show, status: :unprocessable_content
    end
  end

  private

  def set_conversions
    @conversions = VALID_CONVERSIONS
  end

  def perform_conversion(type, value, unit_from, unit_to)
    case type
    when :length
      length_conversion(value, unit_from, unit_to)
    when :weight
      weight_conversion(value, unit_from, unit_to)
    when :temperature
      temperature_conversion(value, unit_from, unit_to)
    when :volume
      volume_conversion(value, unit_from, unit_to)
    else
      "Conversion not supported for type #{type}."
    end
  end

  def length_conversion(value, unit_from, unit_to)
    conversion_factor = {
      "mm" => 0.001, "cm" => 0.01, "m" => 1, "km" => 1000,
      "in" => 0.0254, "ft" => 0.3048, "yd" => 0.9144, "mi" => 1609.34
    }
    convert_with_factor(value, unit_from, unit_to, conversion_factor)
  end

  def weight_conversion(value, unit_from, unit_to)
    conversion_factor = {
      "mg" => 0.000001, "g" => 0.001, "kg" => 1,
      "lb" => 0.453592, "oz" => 0.0283495
    }
    convert_with_factor(value, unit_from, unit_to, conversion_factor)
  end

  def temperature_conversion(value, unit_from, unit_to)
    case [ unit_from, unit_to ]
    when [ "C", "C" ] then value
    when [ "C", "K" ] then value + 273.15
    when [ "K", "C" ] then value - 273.15
    when [ "C", "F" ] then (value * 9 / 5) + 32
    when [ "F", "C" ] then (value - 32) * 5 / 9
    when [ "K", "F" ] then (value - 273.15) * 9 / 5 + 32
    when [ "F", "K" ] then (value - 32) * 5 / 9 + 273.15
    else "Unsupported temperature conversion: #{unit_from} to #{unit_to}"
    end
  end

  def volume_conversion(value, unit_from, unit_to)
    conversion_factor = {
      "ml" => 0.001, "l" => 1, "m3" => 1000, "cm3" => 0.001,
      "gal" => 3.78541, "qt" => 0.946353, "pt" => 0.473176, "fl oz" => 0.0295735
    }
    convert_with_factor(value, unit_from, unit_to, conversion_factor)
  end

  def convert_with_factor(value, unit_from, unit_to, factor)
    if factor[unit_from] && factor[unit_to]
      converted_value = value * (factor[unit_from] / factor[unit_to])
      Rails.logger.debug "#{value} * (#{factor[unit_from]} / #{factor[unit_to]})"
      "#{value} #{unit_from} = #{converted_value.round(2)} #{unit_to}"
    else
      "Invalid conversion units: #{unit_from} to #{unit_to}"
    end
  end
end

unit-converter/app/helpers/application_helper.rb
module ApplicationHelper
end

unit-converter/app/helpers/unit_converter_helper.rb
module UnitConverterHelper
end

unit-converter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Unit Converter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="header-layout">
    <header id="header">
      <div class="container">
        <h1 class="font-bold text-2xl">Unit Converter</h1>
      </div>
    </header>

    <main id="main">
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

unit-converter/app/views/unit_converter/_form.html.erb
<%= form_with url: operation_path, method: :post, class: "card flex flex-col gap" do |form| %>
  <%= hidden_field_tag :type, type %>
  <div class="flex flex-col gap-half">
    <h3 class="text-2xl font-semibold leading-none"><%= type.capitalize %>
      Conversion</h3>
    <p class="text-sm text-subtle">Convert different
      <%= type + "s" %>
      to see their results.</p>
  </div>
  <div class="flex flex-col gap mb-2">
    <div class="flex flex-col gap-half">
      <%= form.label type,
                 "Enter the #{type} to convert",
                 class: "text-sm font-medium leading-none" %>
      <%= form.text_field type, class: "input" %>
    </div>
    <div class="flex flex-col gap-half">
      <%= form.label "unit_from",
                 "Unit to convert from",
                 class: "text-sm font-medium leading-none" %>
      <%= form.select "unit_from", @conversions[type.to_sym], {}, class: "input" %>
    </div>
    <div class="flex flex-col gap-half">
      <%= form.label "unit_to",
                 "Unit to convert to",
                 class: "text-sm font-medium leading-none" %>
      <%= form.select "unit_to", @conversions[type.to_sym], {}, class: "input" %>
    </div>
  </div>
  <div class="flex items-center">
    <%= form.submit "Convert #{type.capitalize}", class: "btn btn--primary" %>
  </div>
<% end %>

unit-converter/app/views/unit_converter/show.html.erb
<turbo-frame id="tabs">
  <div
    class="flex flex-col gap"
    style="max-inline-size: 400px"
    data-controller="tabs"
  >
    <!-- Tab buttons -->
    <div
      class="tabs__list"
      data-action="keydown.left->tabs#prev keydown.right->tabs#next"
      role="tablist"
    >
      <button
        id="trigger_length"
        class="btn btn--tab"
        data-tabs-target="button"
        data-action="tabs#select"
        role="tab"
        aria-controls="tab_length"
      >Length</button>
      <button
        id="trigger_weight"
        class="btn btn--tab"
        data-tabs-target="button"
        data-action="tabs#select"
        role="tab"
        aria-controls="tab_weight"
      >Weight</button>
      <button
        id="trigger_temperature"
        class="btn btn--tab"
        data-tabs-target="button"
        data-action="tabs#select"
        role="tab"
        aria-controls="tab_temperature"
      >Temperature</button>
    </div>
    <!-- Flash Messages -->
    <% if flash[:notice] %>
      <div class="alert alert--positive">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert--negative">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <!-- Results -->
    <% if @results.present? %>
      <div class="results card">
        <h3 class="text-lg font-semibold">Results of your calculation</h3>
        <p class="text-base"><%= @results %></p>
        <%= button_to "Reset",
        root_path,
        type: :reset,
        class: "btn btn--primary",
        method: :get %>
      </div>
    <% else %>
      <!-- Tab Panels -->
      <div
        hidden
        id="tab_length"
        data-tabs-target="tab"
        role="tabpanel"
        tabindex="0"
        aria-labelledby="trigger_length"
      >
        <%= render "form", type: "length" %>
      </div>

      <div
        hidden
        id="tab_weight"
        data-tabs-target="tab"
        role="tabpanel"
        tabindex="0"
        aria-labelledby="trigger_weight"
      >
        <%= render "form", type: "weight" %>
      </div>

      <div
        hidden
        id="tab_temperature"
        data-tabs-target="tab"
        role="tabpanel"
        tabindex="0"
        aria-labelledby="trigger_temperature"
      >
        <%= render "form", type: "temperature" %>
      </div>
    <% end %>
  </div>
</turbo-frame>